# Generated by Django 5.2.6 on 2025-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
