# Generated by Django 5.2.6 on 2025-09-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_matiere_nom_alter_niveau_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='matieres',
        ),
        migrations.AddField(
            model_name='matiere',
            name='eleve',
            field=models.ManyToManyField(to='notes.eleve'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.enseignant'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ManyToManyField(to='notes.niveau'),
        ),
    ]
