# Generated by Django 5.2.6 on 2025-10-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_enseignant_matieres_matiere_eleve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
    ]
