# Generated by Django 5.2.6 on 2025-10-18 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_eleve_options_alter_enseignant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
